MODEL_CHECKPOINT: "%MODEL.CHECKPOINT%"
MODEL_NAME: "%MODEL.NAME%"
IC_NAME: "%MODEL.ICS%"
STD_VERSION: "v000"
INI_DATA_PATH: "%DIRS.INI_DATA_PATH%/%CHUNK_START_DATE%"
START_TIME: '%CHUNK_START_YEAR%-%CHUNK_START_MONTH%-%CHUNK_START_DAY%'
END_TIME: '%CHUNK_END_YEAR%-%CHUNK_END_MONTH%-%CHUNK_END_DAY%'
DATA_INNER_STEPS: 24  
INNER_STEPS: 6        
MEMBERS: "%EXPERIMENT.MEMBERS%"
RNG_KEY: "%MEMBER%"
OUTPUT_PATH: "%HPCROOTDIR%/outputs/%MODEL.NAME%/%MEMBER%/"
TEMP_DIR: "%HPCROOTDIR%/temp/%MODEL.NAME%/%SDATE%/%MEMBER%/"
OUT_VARS: "%EXPERIMENT.OUT_VARS%"
ICS_TEMP_DIR: "%HPCROOTDIR%/ics_temp/%MODEL.NAME%/%SDATE%/ics/"
STATIC_DATA: "%PATHS.STATIC_DATA%"
CLIMATOLOGY_DATA: "%PATHS.CLIMATOLOGY_DATA%"
HPCROOTDIR: "%HPCROOTDIR%"